# Generated by Django 4.2.11 on 2025-06-16 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businesspartner_legacy_id_currency_legacy_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True)),
                ('opportunity_number', models.CharField(help_text='Q #718923 format', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Descriptive name for the opportunity', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost'), ('on_hold', 'On Hold')], default='prospecting', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('probability', models.DecimalField(decimal_places=2, default=0, help_text='Probability of closing (0-100%)', max_digits=5)),
                ('estimated_value_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('estimated_value', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, help_text='Estimated total opportunity value', max_digits=15, null=True)),
                ('actual_value_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('actual_value', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, help_text='Actual closed value', max_digits=15, null=True)),
                ('date_opened', models.DateField(default=django.utils.timezone.now)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Lead source (website, referral, etc.)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Internal notes and updates')),
                ('business_partner', models.ForeignKey(help_text='Primary customer for this opportunity', limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.PROTECT, to='core.businesspartner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-date_opened', 'opportunity_number'],
            },
        ),
    ]
