# Generated by Django 4.2.11 on 2025-06-16 23:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentterms_incoterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartnerLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True)),
                ('name', models.CharField(help_text="Location name (e.g., 'Main Office', 'Warehouse', 'Billing')", max_length=60)),
                ('address1', models.CharField(blank=True, max_length=60, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=60, verbose_name='Address Line 2')),
                ('address3', models.CharField(blank=True, max_length=60, verbose_name='Address Line 3')),
                ('city', models.CharField(blank=True, max_length=60)),
                ('state', models.CharField(blank=True, max_length=40, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('postal_code_add', models.CharField(blank=True, max_length=10, verbose_name='Additional Postal Code')),
                ('country', models.CharField(default='United States', max_length=60)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('phone2', models.CharField(blank=True, max_length=40, verbose_name='Phone 2')),
                ('fax', models.CharField(blank=True, max_length=40)),
                ('is_bill_to', models.BooleanField(default=False, help_text='Billing address')),
                ('is_ship_to', models.BooleanField(default=False, help_text='Shipping address')),
                ('is_pay_from', models.BooleanField(default=False, help_text='Payment address')),
                ('is_remit_to', models.BooleanField(default=False, help_text='Remit-to address')),
                ('comments', models.TextField(blank=True, help_text='Address comments')),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.businesspartner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Partner Location',
                'verbose_name_plural': 'Business Partner Locations',
                'ordering': ['business_partner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True)),
                ('name', models.CharField(help_text='Contact full name', max_length=60)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, help_text='Job title', max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Primary Phone')),
                ('phone2', models.CharField(blank=True, max_length=40, verbose_name='Secondary Phone')),
                ('fax', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('is_sales_lead', models.BooleanField(default=False, help_text='Sales lead contact')),
                ('is_bill_to', models.BooleanField(default=False, help_text='Billing contact')),
                ('is_ship_to', models.BooleanField(default=False, help_text='Shipping contact')),
                ('business_partner', models.ForeignKey(blank=True, help_text='Associated business partner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.businesspartner')),
                ('business_partner_location', models.ForeignKey(blank=True, help_text='Specific location this contact is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businesspartnerlocation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, help_text="Contact's supervisor", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_partner', 'name'],
            },
        ),
    ]
