# Generated by Django 4.2.11 on 2025-06-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_strategic_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-opportunity_number'], 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='actual_close_date',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='actual_value',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='actual_value_currency',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='business_partner',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='date_opened',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='estimated_value',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='estimated_value_currency',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='expected_close_date',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='sales_rep',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='source',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='stage',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this opportunity is currently active'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(help_text='Descriptive name for the opportunity/project', max_length=200),
        ),
    ]
