# Generated by Django 4.2.11 on 2025-06-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_search_key_and_add_code_autogen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspartner',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='state',
        ),
    ]
