# Generated by Django 4.2.11 on 2025-06-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_redundant_address_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='business_partner_location',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_bill_to',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_sales_lead',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_ship_to',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone2',
        ),
    ]
