# Generated by Django 4.2.11 on 2025-06-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_contact_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspartnerlocation',
            name='address3',
        ),
        migrations.RemoveField(
            model_name='businesspartnerlocation',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='businesspartnerlocation',
            name='is_pay_from',
        ),
        migrations.RemoveField(
            model_name='businesspartnerlocation',
            name='is_remit_to',
        ),
        migrations.RemoveField(
            model_name='businesspartnerlocation',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='businesspartnerlocation',
            name='postal_code_add',
        ),
    ]
