# Generated by Django 4.2.11 on 2025-06-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_businesspartnerlocation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='is_orphan',
            field=models.BooleanField(default=False, help_text='Business partner with no locations or related documents - candidate for deletion'),
        ),
    ]
