# Generated by Django 4.2.11 on 2025-06-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pricelistversion',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storagedetail',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
    ]
