# Generated by Django 4.2.11 on 2025-06-16 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businesspartner_legacy_id_currency_legacy_id_and_more'),
        ('inventory', '0002_pricelist_legacy_id_pricelistversion_legacy_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='default_vendor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor_product_no',
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time_days',
            field=models.IntegerField(default=7, help_text='Lead time in days from vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_vendor',
            field=models.ForeignKey(blank=True, help_text='Primary vendor for this product', limit_choices_to={'is_vendor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='core.businesspartner'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_product_code',
            field=models.CharField(blank=True, help_text="Vendor's SKU/Product Code", max_length=100),
        ),
    ]
