# Generated by Django 4.2.11 on 2025-06-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_lead_time_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_bill_of_materials',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_drop_ship',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_purchased',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_stocked',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_verification_required',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_stock_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
    ]
