# Generated by Django 4.2.11 on 2025-06-16 21:43

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_product_code_add_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='list_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='Brief product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Cost'),
        ),
    ]
