# Generated by Django 4.2.11 on 2025-06-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorbillline',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
    ]
