# Generated by Django 4.2.11 on 2025-06-16 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorderline_quantity_on_purchase_order_and_more'),
        ('purchasing', '0002_charge_legacy_id_purchaseorder_legacy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='source_sales_order',
            field=models.ForeignKey(blank=True, help_text='Sales Order that triggered this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='source_sales_order_line',
            field=models.ForeignKey(blank=True, help_text='Specific SO line this PO line fulfills', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesorderline'),
        ),
    ]
