# Generated by Django 4.2.11 on 2025-06-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_opportunity'),
        ('purchasing', '0003_purchaseorderline_source_sales_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='opportunity',
            field=models.ForeignKey(blank=True, help_text='Related opportunity (Q #XXXXXX)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='core.opportunity'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='opportunity',
            field=models.ForeignKey(blank=True, help_text='Related opportunity (Q #XXXXXX)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='core.opportunity'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='opportunity',
            field=models.ForeignKey(blank=True, help_text='Related opportunity (Q #XXXXXX)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='core.opportunity'),
        ),
    ]
