# Generated by Django 4.2.11 on 2025-06-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchaseorder_opportunity_receipt_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='incoterms',
            field=models.CharField(blank=True, help_text='International Commercial Terms (e.g., EXW, FOB, CIF, DDP)', max_length=100),
        ),
    ]
