# Generated by Django 4.2.11 on 2025-06-16 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentterms_incoterms'),
        ('purchasing', '0005_purchaseorder_incoterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='incoterms_location',
            field=models.CharField(blank=True, help_text="Location for incoterms (e.g., 'Miami Port' for EXW Miami Port)", max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='incoterms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.incoterms'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.paymentterms'),
        ),
    ]
