# Generated by Django 4.2.11 on 2025-06-16 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_businesspartnerlocation_contact'),
        ('purchasing', '0006_purchaseorder_incoterms_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_to_location',
            field=models.ForeignKey(blank=True, help_text='Billing address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_bill_to', to='core.businesspartnerlocation'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='business_partner_location',
            field=models.ForeignKey(blank=True, help_text='Primary vendor address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businesspartnerlocation'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Primary vendor contact for this purchase order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contact'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_location',
            field=models.ForeignKey(blank=True, help_text='Shipping address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_ship_to', to='core.businesspartnerlocation'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='bill_to_address',
            field=models.TextField(blank=True, help_text='Legacy billing address text'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ship_to_address',
            field=models.TextField(blank=True, help_text='Legacy shipping address text'),
        ),
    ]
