# Generated by Django 4.2.11 on 2025-06-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_opportunity_options_and_more'),
        ('purchasing', '0011_fix_payment_terms_null_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_customer',
            field=models.ForeignKey(blank=True, help_text='Customer to ship to (for direct shipments)', limit_choices_to={'is_customer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_ship_to_customer', to='core.businesspartner'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ship_to_location',
            field=models.ForeignKey(blank=True, help_text='Shipping address (filtered by ship-to customer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_ship_to', to='core.businesspartnerlocation'),
        ),
    ]
