# Generated by Django 4.2.11 on 2025-06-24 20:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import purchasing.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_businesspartnerlocation_fields'),
        ('inventory', '0008_add_inventory_performance_indexes'),
        ('purchasing', '0012_purchaseorder_ship_to_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency',
            field=models.ForeignKey(default=purchasing.models.get_default_currency, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_ordered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='organization',
            field=models.ForeignKey(default=purchasing.models.get_default_organization, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='price_list',
            field=models.ForeignKey(default=purchasing.models.get_default_purchase_price_list, limit_choices_to={'is_purchase_price_list': True}, on_delete=django.db.models.deletion.PROTECT, to='inventory.pricelist'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(default=purchasing.models.get_default_warehouse, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
    ]
