# Generated by Django 4.2.11 on 2025-06-24 20:52

from django.db import migrations, models
import purchasing.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0013_add_purchase_order_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_ordered',
            field=models.DateField(default=purchasing.models.get_today_date),
        ),
    ]
