# Generated by Django 4.2.11 on 2025-06-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='journalline',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taxcategory',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Original ID from migrated system', max_length=50, null=True),
        ),
    ]
