# Generated by Django 4.2.11 on 2025-06-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoice_legacy_id_invoiceline_legacy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='quantity_on_purchase_order',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity on PO from vendors', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='quantity_to_purchase',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity that needs to be purchased', max_digits=12),
        ),
    ]
