# Generated by Django 4.2.11 on 2025-06-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorderline_quantity_on_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_po_reference',
            field=models.CharField(blank=True, help_text="Customer's PO number", max_length=100),
        ),
    ]
