# Generated by Django 4.2.11 on 2025-06-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_opportunity'),
        ('sales', '0004_salesorder_customer_po_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='opportunity',
            field=models.ForeignKey(blank=True, help_text='Related opportunity (Q #XXXXXX)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.opportunity'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='opportunity',
            field=models.ForeignKey(blank=True, help_text='Related opportunity (Q #XXXXXX)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='core.opportunity'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='opportunity',
            field=models.ForeignKey(blank=True, help_text='Related opportunity (Q #XXXXXX)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='core.opportunity'),
        ),
    ]
