# Generated by Django 4.2.11 on 2025-06-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_invoice_opportunity_salesorder_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='incoterms',
            field=models.CharField(blank=True, help_text='International Commercial Terms (e.g., EXW, FOB, CIF, DDP)', max_length=100),
        ),
    ]
