# Generated by Django 4.2.11 on 2025-06-16 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_businesspartnerlocation_contact'),
        ('sales', '0007_salesorder_incoterms_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_to_location',
            field=models.ForeignKey(blank=True, help_text='Billing address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_bill_to', to='core.businesspartnerlocation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='business_partner_location',
            field=models.ForeignKey(blank=True, help_text='Primary address for this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businesspartnerlocation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Primary contact for this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contact'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='bill_to_location',
            field=models.ForeignKey(blank=True, help_text='Billing address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_bill_to', to='core.businesspartnerlocation'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='business_partner_location',
            field=models.ForeignKey(blank=True, help_text='Primary address for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businesspartnerlocation'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Primary contact for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contact'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='ship_to_location',
            field=models.ForeignKey(blank=True, help_text='Shipping address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_ship_to', to='core.businesspartnerlocation'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='business_partner_location',
            field=models.ForeignKey(blank=True, help_text='Ship-to address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businesspartnerlocation'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Primary contact for this shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contact'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bill_to_address',
            field=models.TextField(blank=True, help_text='Legacy billing address text'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='bill_to_address',
            field=models.TextField(blank=True, help_text='Legacy billing address text'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ship_to_address',
            field=models.TextField(blank=True, help_text='Legacy shipping address text'),
        ),
    ]
