# Generated by Django 4.2.11 on 2025-06-17 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_businesspartnerlocation_contact'),
        ('sales', '0008_invoice_bill_to_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='internal_user',
            field=models.ForeignKey(blank=True, help_text='Our company contact handling this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_as_internal_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='internal_user',
            field=models.ForeignKey(blank=True, help_text='Our company contact handling this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_as_internal_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='internal_user',
            field=models.ForeignKey(blank=True, help_text='Our company contact handling this shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_as_internal_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Customer contact for this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contact'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Customer contact for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contact'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Customer contact for this shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contact'),
        ),
    ]
