# Generated by Django 4.2.11 on 2025-06-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_add_internal_user_to_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='estimated_delivery_weeks',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Estimated delivery time in weeks', null=True, verbose_name='Estimated Delivery (Weeks)'),
        ),
    ]
