# Generated by Django 4.2.11 on 2025-06-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesorder_estimated_delivery_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='32-character transaction code for remote payment system', max_length=32, null=True, unique=True),
        ),
    ]
