# Generated by Django 4.2.11 on 2025-06-24 18:25

from django.db import migrations
import djmoney.models.fields
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_remove_old_customer_po_number'),
    ]

    operations = [
        # First, update any existing NULL price_actual values to 0
        migrations.RunSQL(
            "UPDATE sales_salesorderline SET price_actual = 0.00 WHERE price_actual IS NULL;",
            reverse_sql="-- No reverse needed"
        ),
        # Then alter the field to have a default value
        migrations.AlterField(
            model_name='salesorderline',
            name='price_actual',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=15, default_currency='USD'),
        ),
    ]
