# Generated by Django 4.2.11 on 2025-06-24 18:28

from django.db import migrations
import djmoney.models.fields
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20250624_1825'),
    ]

    operations = [
        # Make price_actual nullable first
        migrations.AlterField(
            model_name='salesorderline',
            name='price_actual',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=15, null=True, blank=True),
        ),
        # Update any NULL values to 0
        migrations.RunSQL(
            "UPDATE sales_salesorderline SET price_actual = 0.00, price_actual_currency = 'USD' WHERE price_actual IS NULL;",
            reverse_sql="-- No reverse needed"
        ),
        # Make it non-nullable again with default
        migrations.AlterField(
            model_name='salesorderline',
            name='price_actual',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=15),
        ),
    ]
